### ISSUE TITLE
We need cat facts about Iggy

### ISSUE THREAD

**Issue by jaymcgrath** [teamtortuga/catfacts#13]
As a consumer of cat facts, I like to know facts about a lot of cats. Iggy is a high profile cat, and when I think about cats, I think about Iggy.

Iggy is a totally rockin' dude! We desperately need some facts about Iggy.

Implementation notes:
Create a directory called Iggy and add markdown-formatted cat facts. 🎸 

Each fact should be in its own markdown file with a numeric title. Check out some other cat facts if you need help with the format.

Acceptance criteria:
Iggy has an entry in cat facts with at least one fact! 🐈

**Comment by jaymcgrath** [comment]
@chonway - wanna tackle this one? It looks like you've already forked the repo, and you definitely know a lot about the Iggster
You should be able to open a PR from outside of the teamtortuga org, LMK if you can't

**Comment by jaymcgrath** [comment]
if you put the text 
```
closes #13
```

in your PR comment, it will auto close this issue

**Comment by chonway** [comment]
What’s the deliverable date on this? My cat related workload is pretty high
right now so take a bit to get to it.
